name: tasty_reciepes
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  cached_network_image: ^3.4.1
  easy_url_launcher: ^0.0.7
  http: ^1.2.2
  flutter:
    sdk: flutter

dev_dependencies:

  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
  fonts:
    - family: 'Funky02'
      fonts:
        - asset: 'assets/fonts/Funky02.ttf'
